{{- if .Values.users.readonly.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cloudsqlinstance.fullname" . }}-secret-postgres-readonly-user
  labels:
    app: {{ template "cloudsqlinstance.fullname" . }}
    release: {{ .Release.Name }}
    component: cloudsqlinstance
    chart: {{ template "cloudsqlinstance.chart" . }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if not .Values.argocd.enabled }}
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
{{- else }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed, BeforeHookCreation
{{- end }}
{{- if .Values.jobs.secret.annotations }}
{{ toYaml .Values.jobs.secret.annotations | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      name: {{ template "cloudsqlinstance.fullname" . }}-secret-postgres-readonly-user
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-secret-init
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.22.1
          command:
            - bash
            - -c
            - |
              kubectl get secret postgresql-readonly-user -o yaml && \
              exit 0 || \
              kubectl create secret generic postgresql-readonly-user --from-literal=username=readonly --from-literal=password=$(head -c 32 /dev/urandom | base64 | tr -d = | tr -dc '[:alnum:]')
{{- end -}}
