apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-secret-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cloudsqlinstance.fullname" . }}
    release: {{ .Release.Name }}
    component: cloudsqlinstance
    chart: {{ template "cloudsqlinstance.chart" . }}
    heritage: {{ .Release.Service }}