{{- if .Values.pubsub.topic.main.enabled }}
apiVersion: pubsub.gcp.crossplane.io/v1alpha1
kind: Topic
metadata:
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    component: topic
    chart: {{ .Chart.Name }}
    chart-version: {{ .Chart.Version }}
    heritage: {{ .Release.Service }}
  name: databand-{{ .Values.clientName }}
spec:
  deletionPolicy: {{ .Values.deletionPolicy }}
  forProvider:
    labels:
      app: databand-{{ .Values.clientName }}
{{- end }}
