apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cloudsqlinstance.fullname" . }}-secret-postgres-exporter
  labels:
    app: {{ template "cloudsqlinstance.fullname" . }}
    release: {{ .Release.Name }}
    component: cloudsqlinstance
    chart: {{ template "cloudsqlinstance.chart" . }}
    heritage: {{ .Release.Service }}
  annotations:
{{- if not .Values.argocd.enabled }}
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
{{- else }}
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed, BeforeHookCreation
{{- end }}
{{- if .Values.jobs.secret.annotations }}
{{ toYaml .Values.jobs.secret.annotations | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      name: {{ template "cloudsqlinstance.fullname" . }}-secret-postgres-exporter
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-secret-init
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.22.1
          command:
            - bash
            - -c
            - |
              kubectl get secret prometheus-postgres-exporter-secret -o yaml && \
              exit 0 || \
              kubectl create secret generic prometheus-postgres-exporter-secret --from-literal=data_source_name=postgresql://$USERNAME:$PASSWORD@$CLOUDSQL_HOST:5432/databand?sslmode=disable
          env:
            - name: CLOUDSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsqlpostgresql-conn
                  key: endpoint
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsqlpostgresql-conn
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsqlpostgresql-conn
                  key: password