apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-secret-init
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cloudsqlinstance.fullname" . }}
    release: {{ .Release.Name }}
    component: cloudsqlinstance
    chart: {{ template "cloudsqlinstance.chart" . }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-secret-init
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-secret-init
  namespace: {{ .Release.Namespace }}
