{{- if and .Values.newrelic.enabled (not .Values.global.onepassword.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-newrelic
data:
  license_key: {{ .Values.newrelic.license_key | b64enc }}
{{- end -}}