{{- if .Values.global.onepassword.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "databand.fullname" . }}-internal-secrets
  labels:
    app: {{ template "databand.fullname" . }}
    release: {{ .Release.Name }}
    component: databand
    chart: {{ template "databand.chart" . }}
    heritage: {{ .Release.Service }}
{{- if .Values.cloudsqlinstance.argocd.enabled }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded, BeforeHookCreation
{{- end }}
spec:
  template:
    metadata:
      name: {{ template "databand.fullname" . }}-internal-secrets
    spec:
      restartPolicy: Never
      {{- if .Values.databand.podSecurityContext }}
      securityContext:
{{ toYaml .Values.databand.podSecurityContext | indent 8 }}
      {{- end }}
      serviceAccountName: databand-secret
      containers:
        - name: kubectl
          {{- if .Values.databand.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.databand.containerSecurityContext | indent 12 }}
          {{- end }}
          image: bitnami/kubectl:1.22.9
          {{- if .Values.global.databand.image.pullPolicy }}
          imagePullPolicy: {{ .Values.global.databand.image.pullPolicy }}
          {{- end }}
          command:
            - bash
            - -c
            - |
              kubectl get secret databand-internal-secrets -o yaml && \
              exit 0 || \
              kubectl create secret generic databand-internal-secrets --from-literal=username=databand \
                  --from-literal=password=$(head -c 32 /dev/urandom | base64 | tr -d =) \
                  --from-literal=DATABAND__CLIENT_ADMIN__USERNAME={{ .Values.web.env }}_admin \
                  --from-literal=DATABAND__CLIENT_ADMIN__PASSWORD=$(head -c 32 /dev/urandom | base64 | tr -d =) \
                  --from-literal=DBND__WEBSERVER__SECRET_KEY=$(head -c 32 /dev/urandom | base64 | tr -d =) \
{{- end -}}