{{- if and .Values.cloudsqlinstance.enabled .Values.global.onepassword.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "databand.fullname" . }}-onepass-db-secrets
  labels:
    app: {{ template "databand.fullname" . }}
    release: {{ .Release.Name }}
    component: databand
    baseComponent: onepasword-db-secrets
    chart: {{ template "databand.chart" . }}
    heritage: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
{{- if .Values.global.onepassword.jobs.db_secret.annotations }}
{{ toYaml .Values.global.onepassword.jobs.db_secret.annotations | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      name: {{ template "databand.fullname" . }}-onepass-db-secrets
    spec:
      restartPolicy: Never
      {{- if .Values.databand.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.databand.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.databand.podSecurityContext }}
      securityContext:
{{ toYaml .Values.databand.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: onepasscli
          {{- if .Values.databand.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.databand.containerSecurityContext | indent 12 }}
          {{- end }}
          image: 1password/op:2.2.0
          {{- if .Values.global.databand.image.pullPolicy }}
          imagePullPolicy: {{ .Values.global.databand.image.pullPolicy}}
          {{- end }}
          command:
            - bash
            - -c
            - |
              export OP_DEVICE=$(head -c 16 /dev/urandom | base32 | tr -d = | tr '[:upper:]' '[:lower:]')
              echo $DEVOPS_PASSWORD | op account add --address $WEBSITE --email $DEVOPS_USERNAME --secret-key $SECRET_KEY --shorthand=databand
              eval $(echo $DEVOPS_PASSWORD | op signin --account databand)
              export CUSTOMER={{ .Values.web.env }}
              op item list --vault "{{ .Values.global.onepassword.vault.db.rw }}" --categories DATABASE | awk -F"   " '{ print $2 }' | grep -i "^ ${CUSTOMER} DB$" && exit 0 || \
              op item create --category "DATABASE" --title "${CUSTOMER^} DB" --tags ${CUSTOMER} --vault "{{ .Values.global.onepassword.vault.db.rw }}" \
                database_type=PostgreSQL hostname=$endpoint port=5432 database=databand username=$username password=$password
          envFrom:
          - secretRef:
              name: onepassword-user
          - secretRef:
              name: cloudsqlpostgresql-conn
{{- end -}}
