{{- if .Values.databand.ha.enabled -}}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{ else }}
apiVersion: policy/v1beta1
{{ end -}}
kind: PodDisruptionBudget
metadata:
  name: {{ template "databand.fullname" . }}-tracking
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "databand.name" . }}
    chart: {{ template "databand.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "databand.name" . }}
      component: tracking
      release: {{ .Release.Name }}
{{ toYaml .Values.tracking.podDisruptionBudget | indent 2 }}
{{- end }}