apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbnd-alertmanager-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "databand.name" . }}
    chart: {{ template "databand.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}