{{- if .Values.global.onepassword.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: databand-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "databand.name" . }}
    chart: {{ template "databand.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}