{{- if and .Values.global.databand.imageCredentials.username .Values.global.databand.imageCredentials.password .Values.global.databand.imageCredentials.registry -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.databand.image.pullSecret }}
{{- if .Values.global.databand.imageCredentials.annotations }}
  annotations:
    {{ range $key, $value := .Values.global.databand.imageCredentials.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
