{{- if and .Values.databand.smtp.enabled (not .Values.global.onepassword.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smtp
data:
  smtp_email_from: {{ .Values.databand.smtp.smtp_email_from | b64enc }}
  smtp_hostname: {{ .Values.databand.smtp.smtp_hostname | b64enc }}
  smtp_apikey_or_username: {{ .Values.databand.smtp.smtp_apikey_or_username | b64enc }}
  smtp_token_or_password: {{ .Values.databand.smtp.smtp_token_or_password | b64enc }}
{{- end -}}