{{- if and .Values.global.databand.sentry.enabled (not .Values.global.onepassword.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sentry
data:
  url: {{ .Values.global.databand.sentry.url | b64enc }}
{{- end -}}
