{{- if and .Values.databand.cloudflare.enabled (not .Values.global.onepassword.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-env
data:
  CF_API_TOKEN: {{ .Values.databand.cloudflare.api_token | b64enc }}
{{- end -}}