{{- if and (index .Values "prometheus-postgres-exporter" "enabled") (not .Values.cloudsqlinstance.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-postgres-exporter-secret
data:
  data_source_name: {{ (include "prometheus-postgres-exporter-sql-connection" .) | b64enc }}
{{- end -}}
