apiVersion: v1
kind: Service
metadata:
  name: {{ template "databand.fullname" . }}-rule-engine
  labels:
    app: {{ template "databand.name" . }}
    component: rule-engine
    chart: {{ template "databand.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  {{- if .Values.rule_engine.service.type }}
  type: {{ .Values.rule_engine.service.type }}
  {{- else }}
  type: {{ .Values.databand.service.type }}
  {{- end }}
  selector:
    app: {{ template "databand.name" . }}
    component: rule-engine
    release: {{ .Release.Name }}
  ports:
    - name: rule-engine
      protocol: TCP
      port: {{ .Values.rule_engine.service.servicePort }}
      targetPort: {{ .Values.rule_engine.service.servicePort }}
{{- if .Values.rule_engine.service.nodePort }}
      nodePort: {{ .Values.rule_engine.service.nodePort }}
{{- end }}
