apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "dbnd-dbt-monitor.fullname" . }}"
  labels:
    app.kubernetes.io/name: "{{ template "dbnd-dbt-monitor.fullname" . }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{- if .Values.databand_access_token }}
  databand_access_token: {{ .Values.databand_access_token | b64enc  }}
  {{- end }}

  {{- if and .Values.sentry.enabled .Values.sentry.url }}
  sentry_url: {{ .Values.sentry.url | b64enc }}
  {{- else if and .Values.global.databand.sentry.enabled .Values.global.databand.sentry.url }}
  sentry_url: {{ .Values.global.databand.sentry.url | b64enc }}
  {{- end -}}
